name: Version Increment on security and maintenance release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Security release'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PUSH_TO_GIT }}
      - run: git config --global user.name 'Fails maintenance bot'
      - run: git config --global user.email 'marten.richter@freenet.de'
      - run: npx browserslist@latest --update-db --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git diff --quiet || (git add package-lock.json && git commit -m "update browserslist")
      - run: npm version patch
      - run: git push